### ISSUE TITLE
Observer takes a long time to timeout download when Sidetree IPFS service is down

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#184]
Encountered unhandled and possibly fatal Observer error, must investigate and fix:
{ FetchError: request to http://127.0.0.1:3009/transactions?since=6398723881959424&transaction-time-hash=00000000000000cf29c6601ab1f7815e69798ad91f09ec03f3620ffb4f2d3f70 failed, reason: socket hang up
    at ClientRequest.<anonymous> (D:\sidetree-core\node_modules\node-fetch\lib\index.js:1444:11)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketOnEnd (_http_client.js:425:9)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to http://127.0.0.1:3009/transactions?since=6398723881959424&transaction-time-hash=00000000000000cf29c6601ab1f7815e69798ad91f09ec03f3620ffb4f2d3f70 failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }

**Comment by thehenrytsai** [comment]
It looks like the log pasted was incorrect, and unable to reproduce the exact bug, but explicitly hanled the case when CAS is not reachable in 3e840e8deac0805b686934af998c7418c0857af1.
